#!/bin/bash

EXPECTED_ARGS=2
E_BADARGS=65

if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: oic host port` {arg}"
  exit $E_BADARGS
fi

git clone git://github.com/ithkuil/cureblog.git sites/$2_$1
echo $2 > myport
cd sites/$2_$1
npm install
nohup ./run &


